### PR TITLE
Fixed the error with parsing the PS classes

### PR DESCRIPTION
**Pull request by integral-llc**
fixed an error in the messaging interface

### CODE REVIEW

**Comment by hansottowirtz** [comment]
Thank you for the PR! Are you sure the message can only be `{[key: string]: any}`? Or should it just be `any`? For example, is a simple string also a valid message? 
E.g. `sendSDKPluginMessage(123, "message")` or `sendSDKPluginMessage(123, 8888)`.

**Comment by integral-llc** [comment]
> Thank you for the PR! Are you sure the message can only be `{[key: string]: any}`? Or should it just be `any`? For example, is a simple string also a valid message? E.g. `sendSDKPluginMessage(123, "message")` or `sendSDKPluginMessage(123, 8888)`.

yes, quite positive, because on the C++ side, all you have is a `PIActionDescriptor descriptor` and to get values from it, you need to use `key/value` approach.
This is a piece of code I used for testing in C++ side
```c
void UXPMessageHandler(PIActionDescriptor descriptor)
{
  LOG << "Received a message from UXP plugin: " << (uint64)descriptor << LOG_NL;
  try {
    std::string sout;
    std::ostringstream fout(sout);
    uint32 descCount = 0;
    uint32 counter = 0;
    if (sPSActionDescriptor->GetCount(descriptor, &descCount))
      return;

    char* keyIDStr = new char[1024];
    if (keyIDStr == NULL)
      return;
    
//    DumpInfoFromDescriptor(descriptor, fout);
    while (counter < descCount) {
      // get the key for this item
      DescriptorKeyID thisKeyID;
      sPSActionDescriptor->GetKey(descriptor, counter, &thisKeyID);

      // get the type for this key
      DescriptorTypeID typeID;
      sPSActionDescriptor->GetType(descriptor, thisKeyID, &typeID);

      // Convert the 'Hash' to a "hashString"
      LongToStr(thisKeyID, "key", keyIDStr, 1024);

      LOG << "Key: " << keyIDStr << LOG_NL;
      counter++;

      if (!stricmp("QC_json", keyIDStr)) {
        uint32 length;
        char *buff;
        sPSActionDescriptor->GetStringLength(descriptor, thisKeyID, &length);
        buff = new char[++length];
        sPSActionDescriptor->GetString(descriptor, thisKeyID, buff, (uint32)length);
        LOG << "JSON: " << length << ", data: " << buff << LOG_NL;
      }
    }
    
    LOG << "Data: " << sout << LOG_NL
      << ", Count: " << descCount
      << LOG_NL;
  }
  catch (std::exception &ex)
  {
    LOG << "An exception occurred. Error: " << ex.what() << LOG_NL;
  }
  catch (...) {
    LOG << "Unknown error ";
  }
}

```

and here is the TS side to send messages
```ts
  const sendCommandToCPlugin = () => {
    const messageContent = {
      SQ_status: 'ok',
      SQ_filter: Math.random() * 100,
      SQ_date: new Date(),
    };
    const toC = {
      ...messageContent,
      QC_json: JSON.stringify(messageContent),
    };
    console.log('Trying to send message to CPlugin');
    const res = messaging.sendSDKPluginMessage(pluginId, toC as never);
    console.log('sendSDKPluginMessage', res, messageContent);
  };

```

all worked pretty well.

**Comment by hansottowirtz** [comment]
Ok great, thanks for the example!

**Comment by hansottowirtz** [comment]
Fixed in 433de77c1, published in `0.0.6-beta.1`

**Pull request closed without merging**
